version: '3.8'

services:
  osm-feature-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped